/**
 * @generated This file is auto-regenerated by the test runner, and auto-formatted by Prettier
 * @format
 **/

import {
  $ASI,
  $COMMENT,
  $COMMENT_HTML,
  $COMMENT_SINGLE,
  $COMMENT_MULTI,
  $CRLF,
  $EOF,
  $ERROR,
  $IDENT,
  $NL,
  $NUMBER,
  $NUMBER_HEX,
  $NUMBER_DEC,
  $NUMBER_BIN,
  $NUMBER_OCT,
  $NUMBER_OLD,
  $PUNCTUATOR,
  $REGEX,
  $REGEXU,
  $SPACE,
  $STRING,
  $STRING_DOUBLE,
  $STRING_SINGLE,
  $TAB,
  $TICK,
  $TICK_BAD_ESCAPE,
  $TICK_BODY,
  $TICK_HEAD,
  $TICK_PURE,
  $TICK_TAIL,
  $WHITE,
} from '../../../src/zetokenizer.mjs';

export default (describe, test) =>
  describe('debugger statement', _ => {
    test('debugger with semi', {
      code: 'debugger;',
      ast: {
        type: 'Program',
        body: [
          {
            type: 'DebuggerStatement',
          },
        ],
      },
      tokens: [$IDENT, $PUNCTUATOR],
    });
    test('debugger without semi at eof', {
      code: 'debugger',
      ast: {
        type: 'Program',
        body: [
          {
            type: 'DebuggerStatement',
          },
        ],
      },
      tokens: [$IDENT, $ASI],
    });
    test('debugger with asi', {
      code: 'debugger\ndebugger;',
      ast: {
        type: 'Program',
        body: [
          {
            type: 'DebuggerStatement',
          },
          {
            type: 'DebuggerStatement',
          },
        ],
      },
      tokens: [$IDENT, $ASI, $IDENT, $PUNCTUATOR],
    });
  });
