/**
 * @generated This file is auto-regenerated by the test runner, and auto-formatted by Prettier
 * @format
 **/

import {
  $ASI,
  $COMMENT,
  $COMMENT_HTML,
  $COMMENT_SINGLE,
  $COMMENT_MULTI,
  $CRLF,
  $EOF,
  $ERROR,
  $IDENT,
  $NL,
  $NUMBER,
  $NUMBER_HEX,
  $NUMBER_DEC,
  $NUMBER_BIN,
  $NUMBER_OCT,
  $NUMBER_OLD,
  $PUNCTUATOR,
  $REGEX,
  $REGEXU,
  $SPACE,
  $STRING,
  $STRING_DOUBLE,
  $STRING_SINGLE,
  $TAB,
  $TICK,
  $TICK_BAD_ESCAPE,
  $TICK_BODY,
  $TICK_HEAD,
  $TICK_PURE,
  $TICK_TAIL,
  $WHITE,
} from '../../../src/zetokenizer.mjs';

export default (describe, test) =>
  describe('true keyword', _ => {
    test('as a statement', {
      code: 'true',
      ast: {
        type: 'Program',
        body: [
          {
            type: 'ExpressionStatement',
            expression: {
              type: 'Literal',
              value: true,
              raw: 'true',
            },
          },
        ],
      },
      tokens: [$IDENT, $ASI],
    });
    test('as an expression', {
      code: '+true',
      ast: {
        type: 'Program',
        body: [
          {
            type: 'ExpressionStatement',
            expression: {
              type: 'UnaryExpression',
              operator: '+',
              prefix: true,
              argument: {
                type: 'Literal',
                value: true,
                raw: 'true',
              },
            },
          },
        ],
      },
      tokens: [$PUNCTUATOR, $IDENT, $ASI],
    });
    describe('regex edge cases', _ => {
      test('division', {
        code: 'true\n/foo;',
        ast: {
          type: 'Program',
          body: [
            {
              type: 'ExpressionStatement',
              expression: {
                type: 'BinaryExpression',
                left: {
                  type: 'Literal',
                  value: true,
                  raw: 'true',
                },
                operator: '/',
                right: {
                  type: 'Identifier',
                  name: 'foo',
                },
              },
            },
          ],
        },
        desc: 'ASI cannot apply so this must be a division which passes because of the `g` "flag"; this is `(true/foo)/g`',
        tokens: [$IDENT, $PUNCTUATOR, $IDENT, $PUNCTUATOR],
      });
      test('regex test bad', {
        code: 'true\n/foo/;',
        throws: 'Expected to parse a value',
        desc: 'ASI cannot apply so this must be a division and it will fail',
        tokens: [],
      });
      test('regex test good', {
        code: 'true\n/foo/g;',
        ast: {
          type: 'Program',
          body: [
            {
              type: 'ExpressionStatement',
              expression: {
                type: 'BinaryExpression',
                left: {
                  type: 'BinaryExpression',
                  left: {
                    type: 'Literal',
                    value: true,
                    raw: 'true',
                  },
                  operator: '/',
                  right: {
                    type: 'Identifier',
                    name: 'foo',
                  },
                },
                operator: '/',
                right: {
                  type: 'Identifier',
                  name: 'g',
                },
              },
            },
          ],
        },
        desc: 'ASI cannot apply so this must be a division which passes because of the `g` "flag"; this is `(true/foo)/g`',
        tokens: [$IDENT, $PUNCTUATOR, $IDENT, $PUNCTUATOR, $IDENT, $PUNCTUATOR],
      });
    });
  });
